In [1]:
import gym
import numpy as np
import cyberbattle

Make two copies of the same environment. Discover NodeA first on `gym_env_a`. It has index 1 internally. Discover NodeB first on `gym_env_b`. It has index 1 internally.

In [2]:
gym_env_a = gym.make("CyberBattleInternalIDError-v0")
gym_env_a.reset()

{'newly_discovered_nodes_count': 0,
 'leaked_credentials': (array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0])),
 'lateral_move': 0,
 'customer_data_found': (0,),
 'escalation': 0,
 'action_mask': {'local_vulnerability': array([[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]),
  'remote_vulnerability': array([[[1],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
  

In [3]:
print(gym_env_a.env._CyberBattleEnv__discovered_nodes)
print(gym_env_a.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_a.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))

['foothold']
0
foothold


In [4]:
vuln_a = {'local_vulnerability': np.array([0, 0])}
gym_env_a.step(vuln_a)

({'newly_discovered_nodes_count': 1,
  'leaked_credentials': (array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0])),
  'lateral_move': 0,
  'customer_data_found': (0,),
  'escalation': 0,
  'action_mask': {'local_vulnerability': array([[1, 1],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]),
   'remote_vulnerability': array([[[1],
           [1],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          

In [5]:
print(gym_env_a.env._CyberBattleEnv__discovered_nodes)
print(gym_env_a.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_a.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))
print(gym_env_a.env._CyberBattleEnv__find_external_index('NodeA'))
print(gym_env_a.env._CyberBattleEnv__internal_node_id_from_external_node_index(1))

['foothold', 'NodeA']
0
foothold
1
NodeA


In [6]:
gym_env_b = gym.make("CyberBattleInternalIDError-v0")
gym_env_b.reset()

{'newly_discovered_nodes_count': 0,
 'leaked_credentials': (array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0])),
 'lateral_move': 0,
 'customer_data_found': (0,),
 'escalation': 0,
 'action_mask': {'local_vulnerability': array([[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]),
  'remote_vulnerability': array([[[1],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
  

In [7]:
print(gym_env_b.env._CyberBattleEnv__discovered_nodes)
print(gym_env_b.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_b.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))

['foothold']
0
foothold


In [8]:
vuln_b = {'local_vulnerability': np.array([0, 1])}
gym_env_b.step(vuln_b)

({'newly_discovered_nodes_count': 1,
  'leaked_credentials': (array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0])),
  'lateral_move': 0,
  'customer_data_found': (0,),
  'escalation': 0,
  'action_mask': {'local_vulnerability': array([[1, 1],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]),
   'remote_vulnerability': array([[[1],
           [1],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          

In [9]:
print(gym_env_b.env._CyberBattleEnv__discovered_nodes)
print(gym_env_b.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_b.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))
print(gym_env_b.env._CyberBattleEnv__find_external_index('NodeB'))
print(gym_env_b.env._CyberBattleEnv__internal_node_id_from_external_node_index(1))

['foothold', 'NodeB']
0
foothold
1
NodeB


`networkx` nodes are equivalent, but interal id is dependent on the order of vulnerability execution.

In [10]:
gym_env_a.env.environment.network.nodes,gym_env_b.env.environment.network.nodes

(NodeView(('NodeA', 'NodeB', 'foothold')),
 NodeView(('NodeA', 'NodeB', 'foothold')))

Action masks are the same although different vulnerabilities are executed and different nodes are discovered.

In [11]:
mask_a=gym_env_a.compute_action_mask()
mask_b=gym_env_b.compute_action_mask()

In [12]:
all(np.array_equal(mask_a[key],mask_b[key]) for key in mask_a)

True

# Between resets on same env

In [13]:
gym_env = gym.make("CyberBattleInternalIDError-v0")
gym_env.reset()

{'newly_discovered_nodes_count': 0,
 'leaked_credentials': (array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0])),
 'lateral_move': 0,
 'customer_data_found': (0,),
 'escalation': 0,
 'action_mask': {'local_vulnerability': array([[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]),
  'remote_vulnerability': array([[[1],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
  

In [14]:
print(gym_env.env._CyberBattleEnv__discovered_nodes)
print(gym_env.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))

['foothold']
0
foothold


In [15]:
gym_env.step(vuln_a)

({'newly_discovered_nodes_count': 1,
  'leaked_credentials': (array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0])),
  'lateral_move': 0,
  'customer_data_found': (0,),
  'escalation': 0,
  'action_mask': {'local_vulnerability': array([[1, 1],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]),
   'remote_vulnerability': array([[[1],
           [1],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          

In [16]:
print(gym_env.env._CyberBattleEnv__discovered_nodes)
print(gym_env.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))
print(gym_env.env._CyberBattleEnv__find_external_index('NodeA'))
print(gym_env.env._CyberBattleEnv__internal_node_id_from_external_node_index(1))

['foothold', 'NodeA']
0
foothold
1
NodeA


In [17]:
gym_env.reset()

{'newly_discovered_nodes_count': 0,
 'leaked_credentials': (array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0])),
 'lateral_move': 0,
 'customer_data_found': (0,),
 'escalation': 0,
 'action_mask': {'local_vulnerability': array([[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]),
  'remote_vulnerability': array([[[1],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
  

In [18]:
gym_env.step(vuln_b)

({'newly_discovered_nodes_count': 1,
  'leaked_credentials': (array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0])),
  'lateral_move': 0,
  'customer_data_found': (0,),
  'escalation': 0,
  'action_mask': {'local_vulnerability': array([[1, 1],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]),
   'remote_vulnerability': array([[[1],
           [1],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          

In [19]:
print(gym_env.env._CyberBattleEnv__discovered_nodes)
print(gym_env.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))
print(gym_env.env._CyberBattleEnv__find_external_index('NodeB'))
print(gym_env.env._CyberBattleEnv__internal_node_id_from_external_node_index(1))

['foothold', 'NodeB']
0
foothold
1
NodeB
