In [29]:
import gym
import numpy as np

Make two copies of the same environment. Discover NodeA first on `gym_env_a`. It has index 1 internally. Discover NodeB first on `gym_env_b`. It has index 1 internally.

In [41]:
gym_env_a = gym.make("CyberBattleInternalIDError-v0")
gym_env_a.reset()

INFO: Resetting the CyberBattle environment


{'newly_discovered_nodes_count': 0,
 'leaked_credentials': (array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0])),
 'lateral_move': 0,
 'customer_data_found': (0,),
 'escalation': 0,
 'action_mask': {'local_vulnerability': array([[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]),
  'remote_vulnerability': array([[[1],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
  

In [42]:
print(gym_env_a.env._CyberBattleEnv__discovered_nodes)
print(gym_env_a.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_a.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))

['foothold']
0
foothold


In [43]:
vuln_a = {'local_vulnerability': np.array([0, 0])}
gym_env_a.step(vuln_a)

INFO: discovered node: NodeA
INFO: GOT REWARD: 


({'newly_discovered_nodes_count': 1,
  'leaked_credentials': (array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0])),
  'lateral_move': 0,
  'customer_data_found': (0,),
  'escalation': 0,
  'action_mask': {'local_vulnerability': array([[1, 1],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]),
   'remote_vulnerability': array([[[1],
           [1],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          

In [44]:
print(gym_env_a.env._CyberBattleEnv__discovered_nodes)
print(gym_env_a.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_a.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))
print(gym_env_a.env._CyberBattleEnv__find_external_index('NodeA'))
print(gym_env_a.env._CyberBattleEnv__internal_node_id_from_external_node_index(1))

['foothold', 'NodeA']
0
foothold
1
NodeA


In [45]:
gym_env_b = gym.make("CyberBattleInternalIDError-v0")
gym_env_b.reset()

INFO: Resetting the CyberBattle environment


{'newly_discovered_nodes_count': 0,
 'leaked_credentials': (array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0]),
  array([0, 0, 0, 0])),
 'lateral_move': 0,
 'customer_data_found': (0,),
 'escalation': 0,
 'action_mask': {'local_vulnerability': array([[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]),
  'remote_vulnerability': array([[[1],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          [0],
  

In [46]:
print(gym_env_b.env._CyberBattleEnv__discovered_nodes)
print(gym_env_b.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_b.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))

['foothold']
0
foothold


In [47]:
vuln_b = {'local_vulnerability': np.array([0, 1])}
gym_env_b.step(vuln_b)

INFO: discovered node: NodeB
INFO: GOT REWARD: 


({'newly_discovered_nodes_count': 1,
  'leaked_credentials': (array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0]),
   array([0, 0, 0, 0])),
  'lateral_move': 0,
  'customer_data_found': (0,),
  'escalation': 0,
  'action_mask': {'local_vulnerability': array([[1, 1],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]),
   'remote_vulnerability': array([[[1],
           [1],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          [[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0]],
   
          

In [48]:
print(gym_env_b.env._CyberBattleEnv__discovered_nodes)
print(gym_env_b.env._CyberBattleEnv__find_external_index('foothold'))
print(gym_env_b.env._CyberBattleEnv__internal_node_id_from_external_node_index(0))
print(gym_env_b.env._CyberBattleEnv__find_external_index('NodeB'))
print(gym_env_b.env._CyberBattleEnv__internal_node_id_from_external_node_index(1))

['foothold', 'NodeB']
0
foothold
1
NodeB


`networkx` nodes are equivalent, but interal id is dependent on the order of vulnerability execution.

In [49]:
gym_env_a.env.environment.network.nodes,gym_env_b.env.environment.network.nodes

(NodeView(('NodeA', 'NodeB', 'foothold')),
 NodeView(('NodeA', 'NodeB', 'foothold')))

Action masks are the same although different vulnerabilities are executed and different nodes are discovered.

In [52]:
mask_a=gym_env_a.compute_action_mask()
mask_b=gym_env_b.compute_action_mask()

In [53]:
all(np.array_equal(mask_a[key],mask_b[key]) for key in mask_a)

True